- ignore: {name: "Use String"}
- extensions:
  - name:
    - ConstraintKinds
    - DataKinds
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveLift
    - DeriveTraversable
    - DerivingStrategies
    - EmptyCase
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - NoImplicitPrelude
    - OverloadedStrings
    - ScopedTypeVariables
    - StandaloneDeriving
    - StrictData
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators
