name:                hex
version:             0.1.0.0
github:              "eddiejessup/hex"
license:             BSD3
author:              "Elliot Marsden"
maintainer:          "elliot.marsden@gmail.com"
copyright:           "Copyright (c) 2017 Elliot Marsden"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/eddiejessup/hex#readme>

dependencies:
- aeson
- base
- binary
- bytestring
- conduit
- conduit-extra
- containers
- directory
- exceptions
- fast-logger
- generic-optics
- generic-random
- hashable
- mono-traversable
- mtl
- optics-core
- optics-extra
- optparse-applicative
- parser-combinators
- path
- path-io
- protolude
- QuickCheck
- text
- time
- transformers
- unordered-containers
- vector

library:
  source-dirs: src

ghc-options:
- -optP-Wno-nonportable-include-path
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-warnings-deprecations
- -Wno-incomplete-patterns
- -Wno-incomplete-uni-patterns
- -Wmissing-deriving-strategies
- -O0
- +RTS -A128m -n2m -RTS
- -j

executables:
  hexc:
    main:                Hexc.hs
    source-dirs:         hexc
    dependencies:
    - hex

  hexi:
    main:                Hexi.hs
    source-dirs:         hexi
    dependencies:
    - hex

tests:
  test:
    main:                Main.hs
    source-dirs:
      - test
      - src
    dependencies:
    - hex
    - tasty
    - tasty-hunit

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
