name:                hex
version:             0.1.0.0
github:              "eddiejessup/hex"
license:             BSD3
author:              "Elliot Marsden"
maintainer:          "elliot.marsden@gmail.com"
copyright:           "Copyright (c) 2017 Elliot Marsden"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/eddiejessup/hex#readme>

dependencies:
- base
- binary
- bytestring
- containers
- directory
- exceptions
- fast-logger
- generic-optics
- generic-random
- hashable
- mono-traversable
- mtl
- optics-core
- parser-combinators
- path
- path-io
- protolude
- QuickCheck
- text
- transformers
- unordered-containers
- vector

library:
  source-dirs: src

ghc-options:
- -optP-Wno-nonportable-include-path
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-warnings-deprecations
- -Wno-incomplete-patterns
- -Wno-incomplete-uni-patterns
- -Wmissing-deriving-strategies
- -O0
- +RTS -A128m -n2m -RTS
- -j

executables:
  app:
    main:                App.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex

  repl:
    main:                Repl.hs
    source-dirs:         repl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex

tests:
  hex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex
    - hspec

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
