name:                hex
version:             0.1.0.0
github:              "eddiejessup/hex"
license:             BSD3
author:              "Elliot Marsden"
maintainer:          "elliot.marsden@gmail.com"
copyright:           "Copyright (c) 2017 Elliot Marsden"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/eddiejessup/hex#readme>

dependencies:
- ascii
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- directory
- either
- extra
- filepath
- hashable
- ilist
- megaparsec
- MissingH
- mtl
- parser-combinators
- path
- path-io
- protolude
- safe
- split
- text
- transformers
- unordered-containers
- vector
- witherable

library:
  source-dirs: src

ghc-options:
- -optP-Wno-nonportable-include-path
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-warnings-deprecations
- -Wno-incomplete-patterns
- -Wno-incomplete-uni-patterns
- -O0
- +RTS -A128m -n2m -RTS
- -j

executables:
  hex:
    main:                HeX.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hex

tests:
  hex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - hex
    - hspec

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
