resolver: lts-12.7

packages:
- .

extra-deps:
- git: git@github.com:eddiejessup/hsdev.git
  commit: 5344c58
- haskell-names-0.9.2
- hformat-0.3.3.0
- simple-log-0.9.6
- text-region-0.3.1.0

extra-package-dbs: []

ghc-options:
  "$everything": -O0 -j4

flags:
  hsdev:
    docs: false
